### ISSUE TITLE
Do I have to call migrateStoreAtUrl:storeType:targetModel:error always?

### ISSUE THREAD

**Issue by Ricardo1980** [alo7/ALO7ProgressiveMigrationManager#3]
Do I have to call migrateStoreAtUrl:storeType:targetModel:error always?
Or should I do something like:

if (migrationRequired) {
migrateStoreAtUrl:storeType:targetModel:error....
}

**Comment by fogisland** [comment]
Yes you should, and the 'migrationRequired' logic has been implemented in NSManagedObjectModel+ALO7Util.h , just try this method:
- (BOOL)ALO7_isMigrationNeededWithStoreType:(NSString *)storeType atPath:(NSString *)storePath;
