### ISSUE TITLE
From model 1 to 3 in one step

### ISSUE THREAD

**Issue by Ricardo1980** [alo7/ALO7ProgressiveMigrationManager#4]
Hello,
Just one question.
Lets say I have 3 models, 1 2 and 3.
All of them use lightweight migration.
Is it normal to see in the console that this library moves from 1 to 3 in one step? (rather than 2 steps like 1 to 2 and 2 to 3).
Thanks.

**Comment by fogisland** [comment]
Yes it`s normal.  
ALO7ProgressiveMigrationStepManager will merge consecutive lightweight migrations into one simple step.
